# Generated by Django 3.2.5 on 2021-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdispatcheractivity_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
            preserve_default=False,
        ),
    ]
