# Generated by Django 3.2.5 on 2021-08-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_historicalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='canceled',
            field=models.BooleanField(null=True, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(null=True, verbose_name='Canceled'),
        ),
    ]
