# Generated by Django 3.2.5 on 2021-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210804_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
    ]
