# Generated by Django 3.2.5 on 2021-08-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('orders', '0018_remove_historicalorder_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='company.company'),
            preserve_default=False,
        ),
    ]
