# Generated by Django 3.2.5 on 2021-08-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210804_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaladdress',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='ip_address',
        ),
    ]
