# Generated by Django 3.2.5 on 2021-08-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0012_auto_20210811_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'company')},
        ),
    ]
