# Generated by Django 3.2.5 on 2021-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='device_api_key',
            field=models.CharField(max_length=150, null=True, verbose_name='Api key'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_api_key',
            field=models.CharField(max_length=150, null=True, verbose_name='Api key'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
