# Generated by Django 3.2.5 on 2021-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210812_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='initial_password',
            field=models.CharField(max_length=128, null=True, verbose_name='Initial password'),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(max_length=128, null=True, verbose_name='Initial password'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Verified'),
        ),
    ]
