# Generated by Django 3.2.5 on 2021-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('event', models.CharField(max_length=50, verbose_name='Event')),
                ('sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('email', models.BooleanField(default=False, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='currency',
            field=models.CharField(choices=[('AMD', 'AMD'), ('USD', 'USD')], default='AMD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='driver_arrived_radius',
            field=models.FloatField(default=0.2, verbose_name='Driver arrived radius'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='driver_office_radius',
            field=models.FloatField(default=0.1, verbose_name='Driver office radius'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='return_countdown_break_duration',
            field=models.IntegerField(default=10, verbose_name='Return countdown break duration'),
        ),
    ]
