# Generated by Django 3.2.5 on 2021-08-02 13:50

from __future__ import unicode_literals

from django.db import migrations


def create_data(apps, schema_editor):
    GeneralSetting = apps.get_model('settings', 'GeneralSettings')
    Terms = apps.get_model('settings', 'Terms')
    Notification = apps.get_model('settings', 'Notification')

    GeneralSetting.objects.create(
        currency='AMD',
        driver_arrived_radius=0.2,
        driver_office_radius=0.1,
        return_countdown_break_duration=10
    )
    Terms.objects.create(
        terms_and_conditions='Terms',
        privacy_policy='Terms'
    )
    Notification.objects.create(
        event='event',
        sms=True,
        email=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210802_1612'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
