# Generated by Django 3.2.5 on 2021-08-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210802_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
