# Generated by Django 3.2.5 on 2021-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0007_auto_20210805_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='company.company'),
            preserve_default=False,
        ),
    ]
