# Generated by Django 3.2.5 on 2021-08-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0008_auto_20210811_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgeneralsettings',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicalterms',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='terms',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='company.company'),
        ),
    ]
