# Generated by Django 3.2.5 on 2021-08-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_historicalbackendemail_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbackendemail',
            name='ip_address',
        ),
    ]
