# Generated by Django 3.2.5 on 2021-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_historicalcashregister_historicaldriversdept_historicaldriversrepayment_historicaldriverssalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcashregister',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldriversdept',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldriversrepayment',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldriverssalary',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
