# Generated by Django 3.2.5 on 2021-08-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20210804_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcashregister',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='historicaldriversdept',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='historicaldriversrepayment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='historicaldriverssalary',
            name='ip_address',
        ),
    ]
