# Generated by Django 3.2.5 on 2021-08-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0004_auto_20210805_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='historicalcashregister',
            name='driver',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cash date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcashregister',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cash date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalCashBox',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created')),
                ('cash_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dispatcher')),
            ],
            options={
                'verbose_name': 'historical cash box',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('cash_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to=settings.AUTH_USER_MODEL, verbose_name='Dispatcher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
