# Generated by Django 3.2.5 on 2021-08-11 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0005_auto_20210809_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Box'},
        ),
        migrations.AlterModelOptions(
            name='historicalcashbox',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cash Box'},
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to=settings.AUTH_USER_MODEL, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to=settings.AUTH_USER_MODEL, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='historicalcashbox',
            name='from_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='historicalcashbox',
            name='to_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='To'),
        ),
    ]
