# Generated by Django 3.2.5 on 2021-08-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finances', '0006_auto_20210811_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcashregister',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
    ]
