# Generated by Django 3.2.5 on 2021-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_historicalattachedfiles_historicaldriverrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalattachedfiles',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldriverrating',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
