# Generated by Django 3.2.5 on 2021-07-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210719_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
